-- drop table if exists users
--
-- create table users
-- (
--     id       integer      not null auto_increment,
--     phone    varchar(14)  not null,
--     password varchar(255) not null,
--         primary key (id)
-- )
-- insert into users(phone, password) values ((1, "123", "pass"))